import type { Equipment } from "./types";

export const EQUIPMENT: Equipment[] = [
  {
    id: "espada-reta",
    name: "Espada Reta Medieval",
    family: "espadas",
    armor: "media",
    rarity: "raro",
    atk: 64,
    def: 8,
    special: "Corte limpo no hitFrame 3",
    slot: "weapon",
    icon32: "icons/espada-reta.png",
    spritePreview: "previews/espada-reta.png",
  },
  {
    id: "escudo-cruz",
    name: "Grande Escudo da Cruz",
    family: "escudos",
    armor: "pesada",
    rarity: "epico",
    atk: 0,
    def: 42,
    special: "Baluarte: +30% block",
    slot: "shield",
    icon32: "icons/escudo-cruz.png",
    spritePreview: "previews/escudo-cruz.png",
  },
  {
    id: "katana-muramasa",
    name: "Katana Muramasa",
    family: "espadas",
    armor: "leve",
    rarity: "lendario",
    atk: 92,
    def: 2,
    special: "Crítico 2.4×",
    slot: "weapon",
    icon32: "icons/katana.png",
    spritePreview: "previews/katana.png",
  },
  {
    id: "pique-vanguarda",
    name: "Pique de Batalha",
    family: "lancas",
    armor: "media",
    rarity: "raro",
    atk: 70,
    def: 10,
    special: "Alcance +1 célula",
    slot: "weapon",
    icon32: "icons/pique.png",
    spritePreview: "previews/pique.png",
  },
  {
    id: "arco-teixo",
    name: "Arco Longo de Teixo",
    family: "arcos",
    armor: "leve",
    rarity: "raro",
    atk: 80,
    def: 0,
    special: "Saraivada em cone",
    slot: "weapon",
    icon32: "icons/arco.png",
    spritePreview: "previews/arco.png",
  },
  {
    id: "machados-gemeos",
    name: "Machados Bípenes Gêmeos",
    family: "machados",
    armor: "media",
    rarity: "epico",
    atk: 88,
    def: 4,
    special: "Fúria: ATQ sobe com HP baixo",
    slot: "weapon",
    icon32: "icons/machados.png",
    spritePreview: "previews/machados.png",
  },
  {
    id: "martelo-fe",
    name: "Martelo Abençoado",
    family: "marretas",
    armor: "pesada",
    rarity: "epico",
    atk: 58,
    def: 18,
    special: "Consagra o chão",
    slot: "weapon",
    icon32: "icons/martelo.png",
    spritePreview: "previews/martelo.png",
  },
  {
    id: "adagas-peconha",
    name: "Adagas Peçonhentas",
    family: "adagas",
    armor: "leve",
    rarity: "lendario",
    atk: 96,
    def: 0,
    special: "Sangramento empilhável",
    slot: "weapon",
    icon32: "icons/adagas.png",
    spritePreview: "previews/adagas.png",
  },
  {
    id: "cajado-eter",
    name: "Cajado Encantado",
    family: "cajados",
    armor: "leve",
    rarity: "epico",
    atk: 84,
    def: 6,
    special: "Ruptura de éter",
    slot: "weapon",
    icon32: "icons/cajado.png",
    spritePreview: "previews/cajado.png",
  },
  {
    id: "escudo-torre",
    name: "Escudo Torre de Platina",
    family: "escudos",
    armor: "pesada",
    rarity: "imortal",
    atk: 8,
    def: 86,
    special: "Muralha viva",
    slot: "shield",
    icon32: "icons/torre.png",
    spritePreview: "previews/torre.png",
  },
  {
    id: "capa-escarlate",
    name: "Capa Escarlate das Cruzadas",
    family: "escudos",
    armor: "media",
    rarity: "raro",
    atk: 0,
    def: 12,
    special: "Identidade do Templário",
    slot: "cape",
    icon32: "icons/capa.png",
    spritePreview: "previews/capa.png",
  },
  {
    id: "elmo-fenda",
    name: "Elmo de Fenda Templário",
    family: "escudos",
    armor: "pesada",
    rarity: "raro",
    atk: 0,
    def: 16,
    slot: "helm",
    icon32: "icons/elmo.png",
    spritePreview: "previews/elmo.png",
  },
];

export const RARITY_LABEL: Record<Equipment["rarity"], string> = {
  basico: "Básico",
  raro: "Raro",
  epico: "Épico",
  lendario: "Lendário",
  imortal: "Imortal",
};

export const FAMILY_LABEL: Record<Equipment["family"], string> = {
  adagas: "Adagas",
  arcos: "Arcos",
  espadas: "Espadas",
  machados: "Machados",
  marretas: "Marretas",
  cajados: "Cajados",
  lancas: "Lanças",
  escudos: "Escudos",
};
