import type { Character, CharacterKit } from "./types";

const rgb = (h: string): [number, number, number] => {
  const n = h.replace("#", "");
  return [
    parseInt(n.slice(0, 2), 16),
    parseInt(n.slice(2, 4), 16),
    parseInt(n.slice(4, 6), 16),
  ];
};

const steel: Pick<CharacterKit, "metal" | "metalLight" | "metalDark" | "leather"> = {
  metal: rgb("#8A96A3"),
  metalLight: rgb("#C5CDD4"),
  metalDark: rgb("#4A5560"),
  leather: rgb("#5C3A1E"),
};

function kit(partial: CharacterKit): CharacterKit {
  return partial;
}

export const ROSTER: Character[] = [
  {
    id: "swordsman",
    name: "Espadachim Real",
    title: "Combate Equilibrado",
    difficulty: "facil",
    role: "Duelista da coroa",
    weapon: "Espada Longa de Aço Nobre",
    lore: "Padrão da coroa. Corte limpo, guarda alta, nada de frescura.",
    stats: { hp: 480, atk: 72, def: 40, spd: 4.4 },
    survivorSkill: { name: "Riposte Real", desc: "O próximo bloqueio devolve 50% do dano." },
    tags: ["Espada", "Equilíbrio", "Coroa"],
    accent: "#3B82F6",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#2B4C8A"),
      clothShadow: rgb("#1B3260"),
      clothLight: rgb("#4E72B8"),
      cape: rgb("#1E3A8A"),
      capeShadow: rgb("#152A66"),
      accent: rgb("#60A5FA"),
      accentDark: rgb("#1D4ED8"),
      helm: "nasal",
      weapon: "sword",
      shield: "none",
      hasCape: false,
    }),
  },
  {
    id: "lancer",
    name: "Lanceiro da Vanguarda",
    title: "Controle de Espaço",
    difficulty: "medio",
    role: "Linha de frente",
    weapon: "Pique de Batalha com Estandarte",
    lore: "Segura a linha. Ninguém passa do alcance do pique.",
    stats: { hp: 520, atk: 70, def: 48, spd: 3.8 },
    survivorSkill: {
      name: "Muralha de Pontas",
      desc: "Aumenta alcance e empurra inimigos por 4s.",
    },
    tags: ["Lança", "Alcance", "Linha de Frente"],
    accent: "#10B981",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#1F6B4A"),
      clothShadow: rgb("#144830"),
      clothLight: rgb("#34A06E"),
      cape: rgb("#14532D"),
      capeShadow: rgb("#0B3B1F"),
      accent: rgb("#86EFAC"),
      accentDark: rgb("#166534"),
      helm: "nasal",
      weapon: "spear",
      shield: "none",
      hasCape: true,
    }),
  },
  {
    id: "ronin",
    name: "Samurai Ronin",
    title: "Vento Fantasma de Hanzo",
    difficulty: "dificil",
    role: "Assassino de corte",
    weapon: "Katana Muramasa Curva",
    lore: "Mestre andarilho das técnicas iaijutsu. Cortes instantâneos, crítico alto.",
    stats: { hp: 410, atk: 92, def: 28, spd: 5.1 },
    survivorSkill: {
      name: "Corte das Mil Pétalas",
      desc: "Desfere 8 golpes críticos instantâneos.",
    },
    tags: ["Katana", "Crítico", "Dash Veloz", "Alto Dano"],
    accent: "#EF4444",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#1A1A1A"),
      clothShadow: rgb("#0A0A0A"),
      clothLight: rgb("#3F3F46"),
      cape: rgb("#7F1D1D"),
      capeShadow: rgb("#450A0A"),
      leather: rgb("#1C1917"),
      accent: rgb("#EF4444"),
      accentDark: rgb("#991B1B"),
      helm: "none",
      weapon: "katana",
      shield: "none",
      hasCape: false,
    }),
  },
  {
    id: "paladin",
    name: "Paladino da Luz Divina",
    title: "Tanque Sagrado",
    difficulty: "facil",
    role: "Tanque sagrado",
    weapon: "Martelo Abençoado & Escudo da Fé",
    lore: "Luz que não recua. O martelo canta, o escudo não racha.",
    stats: { hp: 680, atk: 58, def: 72, spd: 3.2 },
    survivorSkill: {
      name: "Consagração",
      desc: "Cura aliados próximos e queima mortos-vivos.",
    },
    tags: ["Martelo", "Sagrado", "Tanque"],
    accent: "#EAB308",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#F5F0D8"),
      clothShadow: rgb("#C9C09A"),
      clothLight: rgb("#FFFBEB"),
      cape: rgb("#CA8A04"),
      capeShadow: rgb("#854D0E"),
      accent: rgb("#EAB308"),
      accentDark: rgb("#A16207"),
      helm: "crest",
      weapon: "hammer",
      shield: "round",
      hasCape: true,
    }),
  },
  {
    id: "archer",
    name: "Arqueiro Caçador",
    title: "Atirador à Distância",
    difficulty: "medio",
    role: "Kiting à distância",
    weapon: "Arco Longo de Teixo & Aljava",
    lore: "Uma flecha, um problema a menos. Não deixa chegar perto.",
    stats: { hp: 360, atk: 80, def: 22, spd: 4.8 },
    survivorSkill: { name: "Chuva de Teixo", desc: "Dispara uma saraivada em cone." },
    tags: ["Arco", "Kiting", "Precisão"],
    accent: "#22C55E",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#3F6212"),
      clothShadow: rgb("#2A410C"),
      clothLight: rgb("#65A30D"),
      cape: null,
      capeShadow: null,
      leather: rgb("#7C4A1E"),
      accent: rgb("#A3E635"),
      accentDark: rgb("#3F6212"),
      helm: "hood",
      weapon: "bow",
      shield: "none",
      hasCape: false,
    }),
  },
  {
    id: "templar",
    name: "Cavaleiro Templário",
    title: "Guardião das Cruzadas",
    difficulty: "medio",
    role: "Defesa pesada & impacto",
    weapon: "Espada Reta Medieval & Grande Escudo",
    lore: "Visual clássico: túnica branca, cruz vermelha, elmo com fenda e capa escarlate. Implacável contra as trevas.",
    stats: { hp: 610, atk: 64, def: 58, spd: 3.6 },
    survivorSkill: {
      name: "Baluarte Implacável",
      desc: "Torna-se invulnerável por 3s e repele ataques.",
    },
    tags: ["Cruzado", "Capa Vermelha", "Elmo de Ferro", "Referência"],
    accent: "#DC2626",
    layers: {
      shadow: "shadow-elliptic",
      legs: "greaves-steel",
      torso: "surcoat-white-cross",
      cape: "cape-scarlet",
      head: "great-helm-slit",
      weapon: "straight-sword",
      shield: "kite-cross",
    },
    pilot: true,
    kit: kit({
      ...steel,
      cloth: rgb("#F2EDE0"),
      clothShadow: rgb("#C9C0AE"),
      clothLight: rgb("#FFFaf0"),
      cape: rgb("#9B1B1B"),
      capeShadow: rgb("#5C1010"),
      accent: rgb("#C41E3A"),
      accentDark: rgb("#8B1528"),
      helm: "great",
      weapon: "sword",
      shield: "kite",
      hasCape: true,
    }),
  },
  {
    id: "berserker",
    name: "Berserker Nórdico",
    title: "Dano Fúria & Caos",
    difficulty: "dificil",
    role: "Fúria de linha",
    weapon: "Machados Bípenes Gêmeos",
    lore: "Quanto menos vida, mais o machado fala.",
    stats: { hp: 540, atk: 88, def: 30, spd: 4.6 },
    survivorSkill: {
      name: "Fúria do Inverno",
      desc: "ATQ sobe conforme HP cai. Aos 25% HP, hits em área.",
    },
    tags: ["Machado", "Fúria", "Caos"],
    accent: "#F97316",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#7C2D12"),
      clothShadow: rgb("#431407"),
      clothLight: rgb("#C2410C"),
      cape: rgb("#9A3412"),
      capeShadow: rgb("#7C2D12"),
      leather: rgb("#44403C"),
      metal: rgb("#A8A29E"),
      accent: rgb("#F97316"),
      accentDark: rgb("#9A3412"),
      helm: "horns",
      weapon: "axes",
      shield: "none",
      hasCape: false,
    }),
  },
  {
    id: "assassin",
    name: "Assassino das Sombras",
    title: "Furtividade & Veneno",
    difficulty: "mestre",
    role: "Furtivo",
    weapon: "Adagas Gêmeas Peçonhentas",
    lore: "Se você viu o manto, já tomou o segundo corte.",
    stats: { hp: 320, atk: 96, def: 18, spd: 5.6 },
    survivorSkill: {
      name: "Véu de Peçonha",
      desc: "Fica intangível 2s e aplica sangramento empilhável.",
    },
    tags: ["Adaga", "Veneno", "Furtivo"],
    accent: "#A855F7",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#2E1065"),
      clothShadow: rgb("#1C0648"),
      clothLight: rgb("#5B21B6"),
      cape: rgb("#3B0764"),
      capeShadow: rgb("#1E0538"),
      leather: rgb("#1C1917"),
      accent: rgb("#C084FC"),
      accentDark: rgb("#6B21A8"),
      helm: "hood",
      weapon: "daggers",
      shield: "none",
      hasCape: true,
    }),
  },
  {
    id: "battlemage",
    name: "Mago de Batalha",
    title: "Magia Híbrida & Lâmina",
    difficulty: "dificil",
    role: "Híbrido éter",
    weapon: "Cajado Encantado & Espada de Éter",
    lore: "Não escolhe entre livro e aço. Usa os dois no mesmo compasso.",
    stats: { hp: 400, atk: 84, def: 26, spd: 4.2 },
    survivorSkill: {
      name: "Ruptura de Éter",
      desc: "O próximo ataque corpo a corpo explode em área mágica.",
    },
    tags: ["Cajado", "Híbrido", "Éter"],
    accent: "#6366F1",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#312E81"),
      clothShadow: rgb("#1E1B4B"),
      clothLight: rgb("#4F46E5"),
      cape: rgb("#4338CA"),
      capeShadow: rgb("#312E81"),
      accent: rgb("#A5B4FC"),
      accentDark: rgb("#3730A3"),
      helm: "hood",
      weapon: "staff",
      shield: "none",
      hasCape: true,
    }),
  },
  {
    id: "ironward",
    name: "Guardião de Ferro",
    title: "Super Tanque com Escudo Torre",
    difficulty: "facil",
    role: "Super tanque",
    weapon: "Escudo Torre de Platina & Clava",
    lore: "Porta andante. O grupo se esconde atrás dele e agradece.",
    stats: { hp: 760, atk: 48, def: 86, spd: 2.8 },
    survivorSkill: {
      name: "Muralha Viva",
      desc: "Reduz dano do grupo em 40% e taunta inimigos.",
    },
    tags: ["Escudo", "Tanque", "Platino"],
    accent: "#94A3B8",
    layers: {},
    kit: kit({
      ...steel,
      cloth: rgb("#64748B"),
      clothShadow: rgb("#334155"),
      clothLight: rgb("#94A3B8"),
      cape: null,
      capeShadow: null,
      metal: rgb("#CBD5E1"),
      metalLight: rgb("#F1F5F9"),
      metalDark: rgb("#475569"),
      accent: rgb("#E2E8F0"),
      accentDark: rgb("#64748B"),
      helm: "great",
      weapon: "mace",
      shield: "tower",
      hasCape: false,
    }),
  },
];

export const ROSTER_BY_ID: Record<string, Character> = Object.fromEntries(
  ROSTER.map((c) => [c.id, c]),
);

export function getCharacter(id: string): Character {
  return ROSTER_BY_ID[id] ?? ROSTER[5]!;
}
